### ISSUE TITLE
Error: Function name invalid, must be alphanumeric

### ISSUE THREAD

**Issue by obfuscatedgenerated** [MatthewJA/Coffeequate#126]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 Error: Function name invalid, must be alphanumeric
     at new i ([REDACTED]\node_modules\coffeequate\coffeequate.min.js:7:30624)
     at Object.performAction ([REDACTED]\node_modules\coffeequate\coffeequate.min.js:6:5656)
     at n.parse ([REDACTED]\node_modules\coffeequate\coffeequate.min.js:6:8774)
    at Object.stringToExpression ([REDACTED]\node_modules\coffeequate\coffeequate.min.js:6:15896)
    at new e ([REDACTED]\node_modules\coffeequate\coffeequate.min.js:8:1251)
    at o ([REDACTED]\node_modules\coffeequate\coffeequate.min.js:8:4658)
```

**Comment by obfuscatedgenerated** [comment]
I figured out what's going on:
I was passing an expression in the form 2(x+2)
It was treating it as a function instead of as multiplication which is kind of annoying but at least it functions.
